### ISSUE TITLE
CUDA_HOME environment variable is not set.

### ISSUE THREAD

**Issue by itxtayab** [chiehwangs/gaussian-head#13]
python .\submodules\depth-diff-gaussian-rasterization\setup.py install

Traceback (most recent call last):
  File ".\submodules\depth-diff-gaussian-rasterization\setup.py", line 21, in <module>
    CUDAExtension(
  File "C:\Users\muham\anaconda3\envs\ghead\lib\site-packages\torch\utils\cpp_extension.py", line 1048, in CUDAExtension
    library_dirs += library_paths(cuda=True)
  File "C:\Users\muham\anaconda3\envs\ghead\lib\site-packages\torch\utils\cpp_extension.py", line 1186, in library_paths
    paths.append(_join_cuda_home(lib_dir))
  File "C:\Users\muham\anaconda3\envs\ghead\lib\site-packages\torch\utils\cpp_extension.py", line 2223, in _join_cuda_home
    raise EnvironmentError('CUDA_HOME environment variable is not set. '
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.

**Comment by chiehwangs** [comment]
> OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.

I guess it‘s just a CUDA environment issue, [this](https://github.com/graphdeco-inria/gaussian-splatting/issues/520) may help you.

**Comment by itxtayab** [comment]
RuntimeError:
      The detected CUDA version (12.3) mismatches the version that was used to compile
      PyTorch (11.8). Please make sure to use the same CUDA versions.

can you please tell which CUDA version to install?

**Comment by Inferencer** [comment]
> RuntimeError: The detected CUDA version (12.3) mismatches the version that was used to compile PyTorch (11.8). Please make sure to use the same CUDA versions.
> 
> can you please tell which CUDA version to install?

11.8
