### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by Inferencer** [chiehwangs/gaussian-head#4]
Congrats on being the first person to upload code related to Gaussian head avatars, you even beat your timeline for release so that was awesome!

I have a couple of points,
~~the first being the link to the project page on the repo links back to the repo I would be good to see a video example if a project page does exist.~~ **Edit: I just noticed that's on your to-do list so you can ignore this part.**

The second point I would like to bring up is 
I have installed everything correctly and when I run in Windows annaconda
I get the following error message:
```
(gaussian-head) C:\Users\Jack\gaussian-head>python render.py -m ./output/id1
Looking for config file in ./output/id1\cfg_args
Config file found: ./output/id1\cfg_args
Rendering ./output/id1
Loading trained model at iteration 80000 [03/01 16:10:37]
C:\Users\Jack\gaussian-head\data\id1 [03/01 16:10:37]
Traceback (most recent call last):
  File "render.py", line 97, in <module>
    render_sets(model.extract(args), args.iteration, pipeline.extract(args), args.warm_up, args.is_debug, args.skip_train, args.skip_test,
  File "render.py", line 48, in render_sets
    scene = Scene(dataset, gaussians, is_debug=is_debug, novel_view=novel_view, only_head=only_head, load_iteration=iteration, shuffle=False)
  File "C:\Users\Jack\gaussian-head\scene\__init__.py", line 36, in __init__
    assert False, "Could not recognize scene type!"
AssertionError: Could not recognize scene type!
```

**Comment by Inferencer** [comment]
Turns out I didn't download the modified dataset as I skip anything with training written around it and jump straight to inference related stuff, as it contains the `transforms.json` I believe downloading it will solve my issue.
